OrdererOrgs:
  - Name: Orderer
    Domain: gamblar.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.gamblar.com
    EnableNodeOUS: true
    Template:
      Count: 2
    Users:
      Count: 1


  - Name: Org2
    Domain: org2.gamblar.com
    EnableNodeOUS: true
    Template:
      Count: 2
    Users:
      Count: 1